# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: test_api_kikker_development

test:
  <<: *default
  database: test_api_kikker_test

production:
  primary: &primary_production
    <<: *default
    database: test_api_kikker_production
    username: test_api_kikker
    password: <%= ENV["TEST_API_KIKKER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: test_api_kikker_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: test_api_kikker_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: test_api_kikker_production_cable
    migrations_paths: db/cable_migrate
